"""Export the seven remaining project records using only the Python standard library.

Reads this repository's existing front-matter conventions (not a general YAML parser).
Run again when source project copy changes. Existing three curated stories stay in app.js.
"""
from pathlib import Path
import re
import html
import json

ROOT = Path(__file__).resolve().parents[1]
ENTRIES = [
    ('2025-avian-morphing-skeleton-optimisation', 'computation', '在多种性能之间，找到更好的平衡。', 'Find a better balance between competing goals.', '用代理模型与多目标搜索，探索刚度和折叠能力的权衡。', 'Surrogate models and multi-objective search explore stiffness and folding trade-offs.'),
    ('2025-avian-morphing-skeleton-characterisation', 'testing', '展开的每一步，都有力学的答案。', 'Understand the mechanics of every wing pose.', '分离间隙与弹性响应，识别变形骨架的刚度变化和薄弱界面。', 'Separate backlash from elasticity to map rigidity and identify weak interfaces.'),
    ('2024-wraptor-tjoint-substructure-test', 'testing', '让模型，看见真实的缺陷。', 'Let the model see real imperfections.', '用子结构试验与有限元对照，追溯提前软化的制造根因。', 'Compare substructure tests with finite elements to trace early softening to manufacturing.'),
    ('2024-wraptor-tjoint-winding-process', 'manufacturing', '好结构，从纤维浸润开始。', 'Better structures begin with fibre wetting.', '重新设计浸润系统，改善细纤维束缠绕的材料分布与一致性。', 'Redesign the wetting system for more consistent fine-tow winding.'),
    ('2024-wraptor-coaxial-joint-tensile-test', 'testing', '在最薄弱的连接处，加强。', 'Reinforce the weakest connection.', '针对界面脱粘开展拉伸试验，以纤维桥接改善节点强度与一致性。', 'Tensile testing and fibre bridging address debonding, strength and consistency.'),
    ('2023-wraptor-coaxial-joint-cantilever-test', 'testing', '用一次加载，检验一个模型。', 'Put the structural model to the test.', '搭建悬臂试验与测量系统，用实测挠度验证矩阵结构分析。', 'Build a cantilever rig and measurement system to validate matrix structural analysis.'),
    ('2022-wraptor-coaxial-joint-winding-process', 'manufacturing', '一束连续纤维，连接两段桁架。', 'One continuous tow. Two connected trusses.', '从参数化节点到捕束工装，建立同轴节点的连续缠绕制造路线。', 'Develop a continuous winding route, from parametric joints to tow-catching tooling.'),
]

def clean(value):
    return html.unescape(re.sub('<[^>]+>', '', value)).strip()

def scalar(text, name):
    match = re.search(r'^' + name + r':\s*(.+)$', text, re.M)
    if not match:
        raise ValueError(name)
    return match.group(1).strip().strip('"')

def block(text, name):
    return re.search(r'^' + name + r':\s*>-?\n(.*?)(?=^\S|\Z)', text, re.M | re.S).group(1)

result = []
for stem, category, zh_title, en_title, zh_desc, en_desc in ENTRIES:
    path = next((ROOT / '_projects').rglob(stem + '.md'))
    text = path.read_text(encoding='utf-8')
    cover = Path(scalar(text, 'cover')).name
    entry = dict(id=stem, category=category, year=stem[:4], image=cover, source=path.relative_to(ROOT).as_posix())
    for lang, suffix, title, description in [('zh', '_zh', zh_title, zh_desc), ('en', '', en_title, en_desc)]:
        summary = block(text, 'summary' + suffix)
        paragraphs = re.findall(r'<p[^>]*>\s*<strong>(.*?)</strong>\s*(?:&mdash;|—)?\s*(.*?)</p>', summary, re.S)[:3]
        assert len(paragraphs) == 3, stem
        images = re.findall(r'<img[^>]*src="([^"]+)"[^>]*alt="([^"]*)"', summary)
        tags = re.search(r'^tags' + suffix + r':\n((?:[ \t]+-.*\n)+)', text, re.M).group(1)
        tags = [line.strip()[2:] for line in tags.strip().splitlines()]
        slides = []
        for i, (heading, content) in enumerate(paragraphs):
            image_name, caption = (cover, scalar(text, 'title' + suffix)) if i == 0 or not images else (Path(images[min(i-1,len(images)-1)][0]).name, clean(images[min(i-1,len(images)-1)][1]))
            slides.append([['问题', '贡献', '结果'][i] if lang == 'zh' else ['Problem', 'Contribution', 'Result'][i], clean(heading), clean(content), image_name, caption, '摘自现有项目记录。' if lang == 'zh' else 'From the existing project record.'])
        entry[lang] = dict(type=' / '.join(tags[:2]), title=title, titlePlain=scalar(text, 'title' + suffix), description=description, tag=' · '.join(tags[:2]), slides=slides)
    result.append(entry)
(ROOT / '_preview' / 'projects-data.js').write_text('// Generated by sync_projects.py from existing project records.\nconst additionalProjects = ' + json.dumps(result, ensure_ascii=False, indent=2) + ';\n', encoding='utf-8')
print(f'Exported {len(result)} additional projects.')
